In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

Path.cwd()

WindowsPath('d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/notebooks')

In [2]:
file_path = "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/vietnam_transport_cpi_mom_2012_2024.xlsx"
df = pd.read_excel(file_path)

df.head()

,Unnamed: 0,1,2,3,4,5,6,7,8,9,10,11,12
0,2024,100.41,103.09,99.97,101.95,98.27,97.73,101.45,98.02,97.23,100.66,99.93,100.57
1,2023,101.39,102.11,99.84,100.43,97.02,100.16,100.11,103.85,101.21,98.49,99.99,98.12
2,2022,101.18,102.35,104.80,99.41,102.34,103.62,97.15,94.49,97.77,97.83,102.23,97.22
3,2021,102.29,101.55,102.29,100.87,100.76,101.07,102.36,99.94,99.84,102.51,103.11,98.29
4,2020,100.69,97.50,95.13,86.14,97.79,106.05,103.91,100.10,99.88,99.92,99.53,102.45

In [3]:
df.shape

(13, 13)

In [4]:
df.columns

Index(['Unnamed: 0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
       '12'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  13 non-null     int64
 1   1           13 non-null     float64
 2   2           13 non-null     float64
 3   3           13 non-null     float64
 4   4           13 non-null     float64
 5   5           13 non-null     float64
 6   6           13 non-null     float64
 7   7           13 non-null     float64
 8   8           13 non-null     float64
 9   9           13 non-null     float64
 10  10          13 non-null     float64
 11  11          13 non-null     float64
 12  12          13 non-null     float64
dtypes: float64(12), int64(1)
memory usage: 1.4 KB

In [6]:
raw = pd.read_excel(file_path, header=None)

raw.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,1.00,2.00,3.00,4.00,5.00,6.00,7.00,8.00,9.00,10.00,11.00,12.00
1,2024.0,100.41,103.09,99.97,101.95,98.27,97.73,101.45,98.02,97.23,100.66,99.93,100.57
2,2023.0,101.39,102.11,99.84,100.43,97.02,100.16,100.11,103.85,101.21,98.49,99.99,98.12
3,2022.0,101.18,102.35,104.80,99.41,102.34,103.62,97.15,94.49,97.77,97.83,102.23,97.22
4,2021.0,102.29,101.55,102.29,100.87,100.76,101.07,102.36,99.94,99.84,102.51,103.11,98.29

In [14]:
df = raw.copy()

df.columns = [
    "Year",
    "M01", "M02", "M03", "M04",
    "M05", "M06", "M07", "M08",
    "M09", "M10", "M11", "M12"
]

df.head()

,Year,M01,M02,M03,M04,M05,M06,M07,M08,M09,M10,M11,M12
0,NaN,1.00,2.00,3.00,4.00,5.00,6.00,7.00,8.00,9.00,10.00,11.00,12.00
1,2024.0,100.41,103.09,99.97,101.95,98.27,97.73,101.45,98.02,97.23,100.66,99.93,100.57
2,2023.0,101.39,102.11,99.84,100.43,97.02,100.16,100.11,103.85,101.21,98.49,99.99,98.12
3,2022.0,101.18,102.35,104.80,99.41,102.34,103.62,97.15,94.49,97.77,97.83,102.23,97.22
4,2021.0,102.29,101.55,102.29,100.87,100.76,101.07,102.36,99.94,99.84,102.51,103.11,98.29

In [15]:
df = df.drop(index=0).reset_index(drop=True)
df.head()

,Year,M01,M02,M03,M04,M05,M06,M07,M08,M09,M10,M11,M12
0,2024.0,100.41,103.09,99.97,101.95,98.27,97.73,101.45,98.02,97.23,100.66,99.93,100.57
1,2023.0,101.39,102.11,99.84,100.43,97.02,100.16,100.11,103.85,101.21,98.49,99.99,98.12
2,2022.0,101.18,102.35,104.80,99.41,102.34,103.62,97.15,94.49,97.77,97.83,102.23,97.22
3,2021.0,102.29,101.55,102.29,100.87,100.76,101.07,102.36,99.94,99.84,102.51,103.11,98.29
4,2020.0,100.69,97.50,95.13,86.14,97.79,106.05,103.91,100.10,99.88,99.92,99.53,102.45

In [20]:
df = df.apply(
    pd.to_numeric,
    errors="coerce"
)
df.head()

,Year,M01,M02,M03,M04,M05,M06,M07,M08,M09,M10,M11,M12
0,2024.0,100.41,103.09,99.97,101.95,98.27,97.73,101.45,98.02,97.23,100.66,99.93,100.57
1,2023.0,101.39,102.11,99.84,100.43,97.02,100.16,100.11,103.85,101.21,98.49,99.99,98.12
2,2022.0,101.18,102.35,104.80,99.41,102.34,103.62,97.15,94.49,97.77,97.83,102.23,97.22
3,2021.0,102.29,101.55,102.29,100.87,100.76,101.07,102.36,99.94,99.84,102.51,103.11,98.29
4,2020.0,100.69,97.50,95.13,86.14,97.79,106.05,103.91,100.10,99.88,99.92,99.53,102.45

In [21]:
df.isna().sum()

Year    0
M01     0
M02     0
M03     0
M04     0
M05     0
M06     0
M07     0
M08     0
M09     0
M10     0
M11     0
M12     0
dtype: int64

In [22]:
df.shape

(13, 13)

In [25]:
df["Year"] = df["Year"].astype(int)
df["Year"].tolist()
df.head()

,Year,M01,M02,M03,M04,M05,M06,M07,M08,M09,M10,M11,M12
0,2024,100.41,103.09,99.97,101.95,98.27,97.73,101.45,98.02,97.23,100.66,99.93,100.57
1,2023,101.39,102.11,99.84,100.43,97.02,100.16,100.11,103.85,101.21,98.49,99.99,98.12
2,2022,101.18,102.35,104.80,99.41,102.34,103.62,97.15,94.49,97.77,97.83,102.23,97.22
3,2021,102.29,101.55,102.29,100.87,100.76,101.07,102.36,99.94,99.84,102.51,103.11,98.29
4,2020,100.69,97.50,95.13,86.14,97.79,106.05,103.91,100.10,99.88,99.92,99.53,102.45

In [28]:
cpi_long = df.melt(
    id_vars="Year",
    var_name="Month",
    value_name="CPI"
)
cpi_long.head()

   Year Month     CPI
0  2024   M01  100.41
1  2023   M01  101.39
2  2022   M01  101.18
3  2021   M01  102.29
4  2020   M01  100.69

In [30]:
cpi_long["MonthYear"] = pd.to_datetime(
    cpi_long["Year"].astype(int).astype(str) + "-" +
    cpi_long["Month"].str.replace("M", "", regex=False),
    format="%Y-%m"
).dt.to_period("M")
cpi_long.head(15)

    Year Month     CPI MonthYear
0   2024   M01  100.41   2024-01
1   2023   M01  101.39   2023-01
2   2022   M01  101.18   2022-01
3   2021   M01  102.29   2021-01
4   2020   M01  100.69   2020-01
5   2019   M01   96.96   2019-01
6   2018   M01  101.17   2018-01
7   2017   M01  103.21   2017-01
8   2016   M01   97.18   2016-01
9   2015   M01   96.04   2015-01
10  2014   M01  101.22   2014-01
11  2013   M01  100.03   2013-01
12  2012   M01  100.66   2012-01
13  2024   M02  103.09   2024-02
14  2023   M02  102.11   2023-02

In [32]:
cpi_long = cpi_long.sort_values("MonthYear").reset_index(drop=True)
cpi_long.head(15)

    Year Month     CPI MonthYear
0   2012   M01  100.66   2012-01
1   2012   M02  100.23   2012-02
2   2012   M03  101.08   2012-03
3   2012   M04  102.67   2012-04
4   2012   M05  101.32   2012-05
5   2012   M06   98.36   2012-06
6   2012   M07   97.29   2012-07
7   2012   M08  101.07   2012-08
8   2012   M09  103.83   2012-09
9   2012   M10  100.61   2012-10
10  2012   M11  100.03   2012-11
11  2012   M12   99.57   2012-12
12  2013   M01  100.03   2013-01
13  2013   M02  100.81   2013-02
14  2013   M03   99.75   2013-03

In [33]:
print(cpi_long.shape)

(156, 4)

In [34]:
cpi_long = cpi_long.set_index("MonthYear")
cpi_long.head(15)

           Year Month     CPI
MonthYear
2012-01    2012   M01  100.66
2012-02    2012   M02  100.23
2012-03    2012   M03  101.08
2012-04    2012   M04  102.67
2012-05    2012   M05  101.32
2012-06    2012   M06   98.36
2012-07    2012   M07   97.29
2012-08    2012   M08  101.07
2012-09    2012   M09  103.83
2012-10    2012   M10  100.61
2012-11    2012   M11  100.03
2012-12    2012   M12   99.57
2013-01    2013   M01  100.03
2013-02    2013   M02  100.81
2013-03    2013   M03   99.75

In [35]:
cpi_long.dtypes

Year       int64
Month        str
CPI      float64
dtype: object

In [36]:
print(cpi_long.head())
print(cpi_long.tail())

           Year Month     CPI
MonthYear
2012-01    2012   M01  100.66
2012-02    2012   M02  100.23
2012-03    2012   M03  101.08
2012-04    2012   M04  102.67
2012-05    2012   M05  101.32
           Year Month     CPI
MonthYear
2024-08    2024   M08   98.02
2024-09    2024   M09   97.23
2024-10    2024   M10  100.66
2024-11    2024   M11   99.93
2024-12    2024   M12  100.57

In [37]:
cpi_long.to_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/interim/cpi_transport_long.csv",
    encoding="utf-8-sig"
)