In [1]:
import pandas as pd

fuel_1 = pd.read_excel(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/vietnam_fuel_prices_2012_2018.xlsx"
)
fuel_1.head()

,ngay,gio,vung,mat_hang,don_vi,gia_moi,gia_cu,thay_doi,nguon,url
0,01/01/2018,15:00,Vùng 1,Dầu hỏa,Đồng/lít,13610,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
1,01/01/2018,15:00,Vùng 1,"Mazút No2B (3,0S)",Đồng/kg,12530,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
2,01/01/2018,15:00,Vùng 1,"Mazút No2B (3,5S)",Đồng/kg,12380,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
3,01/01/2018,15:00,Vùng 1,Mazút No3 (380),Đồng/kg,12280,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
4,01/01/2018,15:00,Vùng 1,Xăng RON 92,Đồng/lít,18240,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...

In [2]:
fuel_1["ngay"] = pd.to_datetime(
    fuel_1["ngay"],
    dayfirst=True
)
fuel_1.dtypes

ngay        datetime64[us]
gio                    str
vung                   str
mat_hang               str
don_vi                 str
gia_moi             object
gia_cu             float64
thay_doi               str
nguon                  str
url                    str
dtype: object

In [3]:
fuel_1["mat_hang"].unique()

<StringArray>
[                                          'Dầu hỏa',
                                 'Mazút No2B (3,0S)',
                                 'Mazút No2B (3,5S)',
                                   'Mazút No3 (380)',
                                       'Xăng RON 92',
                                       'Xăng RON 95',
                     'Điêzen 0,001S-V (DO 0,001S-V)',
                           'Điêzen 0,05S (DO 0,05S)',
                                      'Điêzen 0,05S',
                                      'Điêzen 0,25S',
                                            'Dauhoa',
                                        'Xăng RON95',
                               'Xăng sinhhocE5RON92',
                                    'Xăng RON 92-II',
                                  'Mazút No2B（3,5S)',
                                  'Mazút No2B(3.0S)',
                                    'Mazút No3(380)',
                                      'Điêzen 0.25S',
                                  'Mazút No2B(3,5S)',
                           'Xăng sinh hoc E5 RON 92',
                                           'E5RON92',
                                    'Xăng RON 95-l1',
                        'Xăng sinh hoc E5 RON 92-ll',
                                  'Mazút No2B(3,0S)',
                                    'Xăng RON 95-II',
                            'Xăng sinhhocE5RON92-Il',
                                     'Xăng RON95-Il',
 '(Ghi chu: Mirc trich ci thyrc hien theo van ban s',
                            'Xăng sinh hoc E5 RON92',
                                     'Xăng RON95-ll',
                                     'Xăng RON95-II',
                            'Xăng sinhhocE5RON92-ll',
                                  'Mazút No2B（3.5S）',
                             'Xăng sinhhocE5RON92-l',
                                  'Mazút No2B（3,5S）',
                                        'Dauhoa d/l',
                                 'Diezencacloai a/l',
                               'Mazut cac loai d/kg',
                                         'angE5 a/1',
                                               'd/l',
                                   'mieniieusinnnoc',
                             'Xăng sinh hocE5RON 92',
                                 'Mazút No2B (3.0S)',
                                  'Mazút No2B（3.0S）',
                                    'Mazút No3(380）',
                                        'Xăng RON92',
                                      'Điêzen 0.05S',
                   'Doiigmmg azut No3 (380) Dong/kg',
                              'ang RON 92  Dongylit',
                                    'au hoa Dong/it',
   'azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka',
              'lezen0,055 buoG iezen 0.25S Dong/lit',
             'Chiahir-Adiuoohioiithuvohi6nthooinhns',
                                              'hanh',
                                    'Mazút No3（380)',
                         'Kang sinh hoc E5 RON95-ll',
                                                'MI',
                                        'ang E5 a/l',
                           'angcacloal(urunmien d/l',
                                         'auhoa d/l',
                                'azut cac loai d/kg',
                                'iezen cac loai d/l',
                                        'usinn noc)',
                               'Xăng sinh hoc E5 RC',
                         'Xăng sinh hoc E5 RON95-ll',
                                    'Xăng RON 95-lI',
                                    'A haa Banallit',
        'Ghichu:Mirctrichcuthurchientheovanbanso54/',
                             'iezencacloai Donqllit',
                              'ng cac loai Dongllit',
                                           'tongikg',
                                       'Xäng RON 95',
                                           'Xăng E5',
                                       'Xăng khoang',
                               'Xăng sinh hoc E5 R(']
Length: 75, dtype: str

In [4]:
print(fuel_1["mat_hang"].value_counts(dropna=False).to_string())

mat_hang
Dầu hỏa                                              183
Xăng RON 95                                          181
Mazút No2B (3,5S)                                    164
Xăng RON 92                                          160
Mazút No2B (3,0S)                                    153
Mazút No3 (380)                                      140
Điêzen 0,05S (DO 0,05S)                               98
Điêzen 0,25S                                          74
Điêzen 0,05S                                          60
Điêzen 0,001S-V (DO 0,001S-V)                         52
Xăng RON 92-II                                        48
Xăng sinh hoc E5 RON 92                               24
Dauhoa                                                19
Xăng sinhhocE5RON92                                   19
Xăng RON95                                            10
Xăng RON95-II                                          9
Điêzen 0.25S                                           7
Xăng sinhhocE5RON92-ll                                 6
Mazút No2B(3,5S)                                       5
Mazút No3(380)                                         4
Xăng sinh hoc E5 RON 92-ll                             4
Xăng sinhhocE5RON92-Il                                 4
Mazút No2B（3,5S)                                       3
Mazút No2B(3,0S)                                       3
Xăng RON 95-II                                         3
Điêzen 0.05S                                           3
Xăng sinh hoc E5 RC                                    3
(Ghi chu: Mirc trich ci thyrc hien theo van ban s      2
Xăng RON95-ll                                          2
Mazút No2B（3.5S）                                       2
Mazút No2B（3,5S）                                       2
Dauhoa d/l                                             2
Diezencacloai a/l                                      2
Mazut cac loai d/kg                                    2
angE5 a/1                                              2
d/l                                                    2
Mazút No2B (3.0S)                                      2
Xăng RON92                                             2
Doiigmmg azut No3 (380) Dong/kg                        2
ang RON 92  Dongylit                                   2
au hoa Dong/it                                         2
azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka        2
lezen0,055 buoG iezen 0.25S Dong/lit                   2
MI                                                     2
ang E5 a/l                                             2
angcacloal(urunmien d/l                                2
auhoa d/l                                              2
azut cac loai d/kg                                     2
iezen cac loai d/l                                     2
A haa Banallit                                         2
Ghichu:Mirctrichcuthurchientheovanbanso54/             2
iezencacloai Donqllit                                  2
ng cac loai Dongllit                                   2
Mazút No2B(3.0S)                                       1
E5RON92                                                1
Xăng RON 95-l1                                         1
Xăng RON95-Il                                          1
Xăng sinh hoc E5 RON92                                 1
Xăng sinhhocE5RON92-l                                  1
mieniieusinnnoc                                        1
Xăng sinh hocE5RON 92                                  1
Mazút No2B（3.0S）                                       1
Mazút No3(380）                                         1
Chiahir-Adiuoohioiithuvohi6nthooinhns                  1
hanh                                                   1
Mazút No3（380)                                         1
Kang sinh hoc E5 RON95-ll                              1
usinn noc)                                             1
Xăng sinh hoc E5 RON95-ll                              1
Xăng RON 95-lI                                         1
tongikg                                                1
Xäng RON 95                                            1
Xăng E5                                                1
Xăng khoang                                            1
Xăng sinh hoc E5 R(                                    1

In [5]:
import unicodedata

fuel_1["mat_hang_clean"] = (
    fuel_1["mat_hang"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize("NFKC", x))
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)
print(fuel_1["mat_hang_clean"].value_counts().to_string())

mat_hang_clean
Dầu hỏa                                              183
Xăng RON 95                                          181
Mazút No2B (3,5S)                                    164
Xăng RON 92                                          160
Mazút No2B (3,0S)                                    153
Mazút No3 (380)                                      140
Điêzen 0,05S (DO 0,05S)                               98
Điêzen 0,25S                                          74
Điêzen 0,05S                                          60
Điêzen 0,001S-V (DO 0,001S-V)                         52
Xăng RON 92-II                                        48
Xăng sinh hoc E5 RON 92                               24
Dauhoa                                                19
Xăng sinhhocE5RON92                                   19
Xăng RON95                                            10
Mazút No2B(3,5S)                                      10
Xăng RON95-II                                          9
Điêzen 0.25S                                           7
Mazút No3(380)                                         6
Xăng sinhhocE5RON92-ll                                 6
Xăng sinh hoc E5 RON 92-ll                             4
Xăng sinhhocE5RON92-Il                                 4
Mazút No2B(3,0S)                                       3
Xăng RON 95-II                                         3
Điêzen 0.05S                                           3
Xăng sinh hoc E5 RC                                    3
Mazút No2B(3.0S)                                       2
(Ghi chu: Mirc trich ci thyrc hien theo van ban s      2
Xăng RON95-ll                                          2
Mazút No2B(3.5S)                                       2
Dauhoa d/l                                             2
Diezencacloai a/l                                      2
Mazut cac loai d/kg                                    2
angE5 a/1                                              2
d/l                                                    2
Mazút No2B (3.0S)                                      2
Xăng RON92                                             2
Doiigmmg azut No3 (380) Dong/kg                        2
ang RON 92 Dongylit                                    2
au hoa Dong/it                                         2
azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka        2
lezen0,055 buoG iezen 0.25S Dong/lit                   2
MI                                                     2
ang E5 a/l                                             2
angcacloal(urunmien d/l                                2
auhoa d/l                                              2
azut cac loai d/kg                                     2
iezen cac loai d/l                                     2
A haa Banallit                                         2
Ghichu:Mirctrichcuthurchientheovanbanso54/             2
iezencacloai Donqllit                                  2
ng cac loai Dongllit                                   2
E5RON92                                                1
Xăng RON 95-l1                                         1
Xăng RON95-Il                                          1
Xăng sinh hoc E5 RON92                                 1
Xăng sinhhocE5RON92-l                                  1
mieniieusinnnoc                                        1
Xăng sinh hocE5RON 92                                  1
Chiahir-Adiuoohioiithuvohi6nthooinhns                  1
hanh                                                   1
Kang sinh hoc E5 RON95-ll                              1
usinn noc)                                             1
Xăng sinh hoc E5 RON95-ll                              1
Xăng RON 95-lI                                         1
tongikg                                                1
Xäng RON 95                                            1
Xăng E5                                                1
Xăng khoang                                            1
Xăng sinh hoc E5 R(                                    1

In [6]:
fuel_1["mat_hang_clean"] = fuel_1["mat_hang_clean"].replace({
    "Xäng RON 95": "Xăng RON 95",
    "Xăng khoang": "Xăng khoáng"
})
print(
    fuel_1.loc[
        fuel_1["mat_hang_clean"].str.contains("Xăng", case=False, na=False),
        "mat_hang_clean"
    ].value_counts().to_string()
)

mat_hang_clean
Xăng RON 95                   182
Xăng RON 92                   160
Xăng RON 92-II                 48
Xăng sinh hoc E5 RON 92        24
Xăng sinhhocE5RON92            19
Xăng RON95                     10
Xăng RON95-II                   9
Xăng sinhhocE5RON92-ll          6
Xăng sinh hoc E5 RON 92-ll      4
Xăng sinhhocE5RON92-Il          4
Xăng RON 95-II                  3
Xăng sinh hoc E5 RC             3
Xăng RON95-ll                   2
Xăng RON92                      2
Xăng RON 95-l1                  1
Xăng RON95-Il                   1
Xăng sinh hoc E5 RON92          1
Xăng sinhhocE5RON92-l           1
Xăng sinh hocE5RON 92           1
Xăng sinh hoc E5 RON95-ll       1
Xăng RON 95-lI                  1
Xăng E5                         1
Xăng khoáng                     1
Xăng sinh hoc E5 R(             1

In [7]:
fuel_1["mat_hang_clean"] = fuel_1["mat_hang_clean"].replace({
    # RON 95
    "Xăng RON95": "Xăng RON 95",
    "Xăng RON95-II": "Xăng RON 95-II",
    "Xăng RON95-ll": "Xăng RON 95-II",
    "Xăng RON95-Il": "Xăng RON 95-II",
    "Xăng RON 95-l1": "Xăng RON 95-II",
    "Xăng RON 95-lI": "Xăng RON 95-II",

    # RON 92
    "Xăng RON92": "Xăng RON 92",

    # E5 RON 92
    "Xăng sinhhocE5RON92": "Xăng sinh học E5 RON 92",
    "Xăng sinh hoc E5 RON 92": "Xăng sinh học E5 RON 92",
    "Xăng sinh hoc E5 RON92": "Xăng sinh học E5 RON 92",
    "Xăng sinh hocE5RON 92": "Xăng sinh học E5 RON 92",

    # E5 RON 92-II
    "Xăng sinhhocE5RON92-ll": "Xăng sinh học E5 RON 92-II",
    "Xăng sinhhocE5RON92-Il": "Xăng sinh học E5 RON 92-II",
    "Xăng sinhhocE5RON92-l": "Xăng sinh học E5 RON 92-II",
    "Xăng sinh hoc E5 RON 92-ll": "Xăng sinh học E5 RON 92-II"
})

print(
    fuel_1["mat_hang_clean"]
    .value_counts()
    .to_string()
)

mat_hang_clean
Xăng RON 95                                          192
Dầu hỏa                                              183
Mazút No2B (3,5S)                                    164
Xăng RON 92                                          162
Mazút No2B (3,0S)                                    153
Mazút No3 (380)                                      140
Điêzen 0,05S (DO 0,05S)                               98
Điêzen 0,25S                                          74
Điêzen 0,05S                                          60
Điêzen 0,001S-V (DO 0,001S-V)                         52
Xăng RON 92-II                                        48
Xăng sinh học E5 RON 92                               45
Dauhoa                                                19
Xăng RON 95-II                                        17
Xăng sinh học E5 RON 92-II                            15
Mazút No2B(3,5S)                                      10
Điêzen 0.25S                                           7
Mazút No3(380)                                         6
Mazút No2B(3,0S)                                       3
Điêzen 0.05S                                           3
Xăng sinh hoc E5 RC                                    3
Mazút No2B(3.0S)                                       2
(Ghi chu: Mirc trich ci thyrc hien theo van ban s      2
Mazút No2B(3.5S)                                       2
Dauhoa d/l                                             2
Diezencacloai a/l                                      2
Mazut cac loai d/kg                                    2
angE5 a/1                                              2
d/l                                                    2
Mazút No2B (3.0S)                                      2
Doiigmmg azut No3 (380) Dong/kg                        2
ang RON 92 Dongylit                                    2
au hoa Dong/it                                         2
azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka        2
lezen0,055 buoG iezen 0.25S Dong/lit                   2
MI                                                     2
ang E5 a/l                                             2
angcacloal(urunmien d/l                                2
auhoa d/l                                              2
azut cac loai d/kg                                     2
iezen cac loai d/l                                     2
A haa Banallit                                         2
Ghichu:Mirctrichcuthurchientheovanbanso54/             2
iezencacloai Donqllit                                  2
ng cac loai Dongllit                                   2
E5RON92                                                1
mieniieusinnnoc                                        1
Chiahir-Adiuoohioiithuvohi6nthooinhns                  1
hanh                                                   1
Kang sinh hoc E5 RON95-ll                              1
usinn noc)                                             1
Xăng sinh hoc E5 RON95-ll                              1
tongikg                                                1
Xăng E5                                                1
Xăng khoáng                                            1
Xăng sinh hoc E5 R(                                    1

In [9]:
fuel_1["mat_hang_clean"] = fuel_1["mat_hang_clean"].replace({
    # Dầu hỏa
    "Dauhoa": "Dầu hỏa",

    # Mazút No2B (3,5S)
    "Mazút No2B(3,5S)": "Mazút No2B (3,5S)",
    "Mazút No2B(3.5S)": "Mazút No2B (3,5S)",

    # Mazút No2B (3,0S)
    "Mazút No2B(3,0S)": "Mazút No2B (3,0S)",
    "Mazút No2B(3.0S)": "Mazút No2B (3,0S)",

    # Mazút No3 (380)
    "Mazút No3(380)": "Mazút No3 (380)",

    # Điêzen
    "Điêzen 0.25S": "Điêzen 0,25S",
    "Điêzen 0.05S": "Điêzen 0,05S"
})

print(fuel_1["mat_hang_clean"].value_counts().to_string())

mat_hang_clean
Dầu hỏa                                              202
Xăng RON 95                                          192
Mazút No2B (3,5S)                                    176
Xăng RON 92                                          162
Mazút No2B (3,0S)                                    158
Mazút No3 (380)                                      146
Điêzen 0,05S (DO 0,05S)                               98
Điêzen 0,25S                                          81
Điêzen 0,05S                                          63
Điêzen 0,001S-V (DO 0,001S-V)                         52
Xăng RON 92-II                                        48
Xăng sinh học E5 RON 92                               45
Xăng RON 95-II                                        17
Xăng sinh học E5 RON 92-II                            15
Xăng sinh hoc E5 RC                                    3
(Ghi chu: Mirc trich ci thyrc hien theo van ban s      2
Dauhoa d/l                                             2
Diezencacloai a/l                                      2
Mazut cac loai d/kg                                    2
angE5 a/1                                              2
d/l                                                    2
Mazút No2B (3.0S)                                      2
Doiigmmg azut No3 (380) Dong/kg                        2
ang RON 92 Dongylit                                    2
au hoa Dong/it                                         2
azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka        2
lezen0,055 buoG iezen 0.25S Dong/lit                   2
MI                                                     2
ang E5 a/l                                             2
angcacloal(urunmien d/l                                2
auhoa d/l                                              2
azut cac loai d/kg                                     2
iezen cac loai d/l                                     2
A haa Banallit                                         2
Ghichu:Mirctrichcuthurchientheovanbanso54/             2
iezencacloai Donqllit                                  2
ng cac loai Dongllit                                   2
E5RON92                                                1
mieniieusinnnoc                                        1
Chiahir-Adiuoohioiithuvohi6nthooinhns                  1
hanh                                                   1
Kang sinh hoc E5 RON95-ll                              1
usinn noc)                                             1
Xăng sinh hoc E5 RON95-ll                              1
tongikg                                                1
Xăng E5                                                1
Xăng khoáng                                            1
Xăng sinh hoc E5 R(                                    1

In [10]:
suspect = fuel_1[
    fuel_1["mat_hang_clean"].isin([
        "Xăng sinh hoc E5 RC",
        "(Ghi chu: Mirc trich ci thyrc hien theo van ban s",
        "Dauhoa d/l",
        "Diezencacloai a/l",
        "Mazut cac loai d/kg",
        "angE5 a/1",
        "d/l",
        "Mazút No2B (3.0S)",
        "Doiigmmg azut No3 (380) Dong/kg",
        "ang RON 92 Dongylit",
        "tongikg",
        "Xăng E5",
        "Xăng khoáng",
        "Xăng sinh hoc E5 R("
    ])
]

suspect

,ngay,gio,vung,mat_hang,don_vi,gia_moi,gia_cu,thay_doi,nguon,url,mat_hang_clean
176,2015-02-05,15:00,Vùng 1,(Ghi chu: Mirc trich ci thyrc hien theo van ban s,Đồng/lít,687,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,(Ghi chu: Mirc trich ci thyrc hien theo van ban s
182,2015-02-05,15:00,Vùng 2,(Ghi chu: Mirc trich ci thyrc hien theo van ban s,Đồng/lít,21012015,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,(Ghi chu: Mirc trich ci thyrc hien theo van ban s
303,2016-12-05,19:00,Vùng 1,Dauhoa d/l,Đồng/lít,nguyen,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Dauhoa d/l
304,2016-12-05,19:00,Vùng 1,Diezencacloai a/l,Đồng/lít,GIUP nguyen,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Diezencacloai a/l
306,2016-12-05,19:00,Vùng 1,Mazut cac loai d/kg,Đồng/lít,h ngu e n,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Mazut cac loai d/kg
310,2016-12-05,19:00,Vùng 1,angE5 a/1,Đồng/lít,e,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,angE5 a/1
311,2016-12-05,19:00,Vùng 1,d/l,Đồng/lít,GiC nguyén,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,d/l
312,2016-12-05,19:00,Vùng 2,Dauhoa d/l,Đồng/lít,3 0 0,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Dauhoa d/l
313,2016-12-05,19:00,Vùng 2,Diezencacloai a/l,Đồng/lít,NaN,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Diezencacloai a/l
314,2016-12-05,19:00,Vùng 2,Mazut cac loai d/kg,Đồng/lít,NaN,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Mazut cac loai d/kg
315,2016-12-05,19:00,Vùng 2,angE5 a/1,Đồng/lít,5,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,angE5 a/1
316,2016-12-05,19:00,Vùng 2,d/l,Đồng/lít,500 50 00,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,d/l
534,2013-10-07,20:00,Vùng 2,Mazút No2B (3.0S),Đồng/kg,19180,19180.0,+0,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Mazút No2B (3.0S)
662,2013-11-11,20:00,Vùng 1,Mazút No2B (3.0S),Đồng/kg,18810,18810.0,+0,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Mazút No2B (3.0S)
839,2014-03-19,12:00,Vùng 1,Doiigmmg azut No3 (380) Dong/kg,Đồng/lít,0,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Doiigmmg azut No3 (380) Dong/kg
844,2014-03-19,12:00,Vùng 1,ang RON 92 Dongylit,Đồng/lít,300,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,ang RON 92 Dongylit
851,2014-03-19,12:00,Vùng 2,Doiigmmg azut No3 (380) Dong/kg,Đồng/lít,Ngirng : siP dur,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Doiigmmg azut No3 (380) Dong/kg
858,2014-03-19,12:00,Vùng 2,ang RON 92 Dongylit,Đồng/lít,0,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,ang RON 92 Dongylit
914,2014-09-19,15:00,Vùng 1,Xăng sinh hoc E5 RC,Đồng/lít,23710,23710.0,+0,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Xăng sinh hoc E5 RC
923,2014-09-19,15:00,Vùng 2,Xăng sinh hoc E5 RC,Đồng/lít,24180,24180.0,+0,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Xăng sinh hoc E5 RC
1090,2015-01-21,16:00,Vùng 2,tongikg,Đồng/lít,NaN,NaN,NaN,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,tongikg
1382,2015-03-26,15:00,Vùng 1,Xăng E5,Đồng/lít,1020,1852.0,-832,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Xăng E5
1383,2015-03-26,15:00,Vùng 1,Xăng khoang,Đồng/lít,1020,1852.0,-832,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Xăng khoáng
1487,2014-09-30,15:00,Vùng 1,Xăng sinh hoc E5 R(,Đồng/lít,23560,23710.0,-150,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Xăng sinh hoc E5 R(
1496,2014-09-30,15:00,Vùng 2,Xăng sinh hoc E5 RC,Đồng/lít,24030,24180.0,-150,Petrolimex,https://www.petrolimex.com.vn/ndi/thong-cao-ba...,Xăng sinh hoc E5 RC

In [11]:
bad_rows = [
    176, 182,
    303, 304, 306, 310, 311, 312, 313, 314, 315, 316,
    839, 844, 851, 858,
    1090,
    1382, 1383
]

fuel_1 = fuel_1.drop(index=bad_rows)
fuel_1 = fuel_1.reset_index(drop=True)

In [14]:
fuel_1.loc[
    fuel_1["mat_hang_clean"].isin([
        "Xăng sinh hoc E5 RC",
        "Xăng sinh hoc E5 R("
    ]),
    ["ngay", "vung", "mat_hang", "gia_moi", "gia_cu", "thay_doi"]
]

           ngay    vung             mat_hang gia_moi   gia_cu thay_doi
898  2014-09-19  Vùng 1  Xăng sinh hoc E5 RC   23710  23710.0       +0
907  2014-09-19  Vùng 2  Xăng sinh hoc E5 RC   24180  24180.0       +0
1468 2014-09-30  Vùng 1  Xăng sinh hoc E5 R(   23560  23710.0     -150
1477 2014-09-30  Vùng 2  Xăng sinh hoc E5 RC   24030  24180.0     -150

In [15]:
fuel_1["mat_hang_clean"] = fuel_1["mat_hang_clean"].replace({
    "Xăng sinh hoc E5 RC": "Xăng sinh học E5 RON 92",
    "Xăng sinh hoc E5 R(": "Xăng sinh học E5 RON 92"
})
fuel_1["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu hỏa                                            202
Xăng RON 95                                        192
Mazút No2B (3,5S)                                  176
Xăng RON 92                                        162
Mazút No2B (3,0S)                                  158
Mazút No3 (380)                                    146
Điêzen 0,05S (DO 0,05S)                             98
Điêzen 0,25S                                        81
Điêzen 0,05S                                        63
Điêzen 0,001S-V (DO 0,001S-V)                       52
Xăng sinh học E5 RON 92                             49
Xăng RON 92-II                                      48
Xăng RON 95-II                                      17
Xăng sinh học E5 RON 92-II                          15
Mazút No2B (3.0S)                                    2
au hoa Dong/it                                       2
azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka      2
lezen0,055 buoG iezen 0.25S Dong/lit                 2
MI                                                   2
ang E5 a/l                                           2
angcacloal(urunmien d/l                              2
auhoa d/l                                            2
azut cac loai d/kg                                   2
iezen cac loai d/l                                   2
A haa Banallit                                       2
Ghichu:Mirctrichcuthurchientheovanbanso54/           2
iezencacloai Donqllit                                2
ng cac loai Dongllit                                 2
E5RON92                                              1
mieniieusinnnoc                                      1
Chiahir-Adiuoohioiithuvohi6nthooinhns                1
hanh                                                 1
Kang sinh hoc E5 RON95-ll                            1
usinn noc)                                           1
Xăng sinh hoc E5 RON95-ll                            1
Name: count, dtype: int64

In [16]:
counts = fuel_1["mat_hang_clean"].value_counts()

rare_names = counts[counts <= 2].index

rare_rows = fuel_1[
    fuel_1["mat_hang_clean"].isin(rare_names)
][
    ["ngay", "vung", "mat_hang", "mat_hang_clean", "don_vi", "gia_moi", "gia_cu", "thay_doi"]
]

rare_rows

,ngay,vung,mat_hang,mat_hang_clean,don_vi,gia_moi,gia_cu,thay_doi
122,2016-03-04,Vùng 1,E5RON92,E5RON92,Đồng/lít,13320,13580.0,+5
305,2016-12-05,Vùng 2,mieniieusinnnoc,mieniieusinnnoc,Đồng/lít,NaN,NaN,NaN
522,2013-10-07,Vùng 2,Mazút No2B (3.0S),Mazút No2B (3.0S),Đồng/kg,19180,19180.0,+0
650,2013-11-11,Vùng 1,Mazút No2B (3.0S),Mazút No2B (3.0S),Đồng/kg,18810,18810.0,+0
831,2014-03-19,Vùng 1,au hoa Dong/it,au hoa Dong/it,Đồng/lít,110,NaN,NaN
832,2014-03-19,Vùng 1,"azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka","azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka",Đồng/lít,0,NaN,NaN
833,2014-03-19,Vùng 1,"lezen0,055 buoG iezen 0.25S Dong/lit","lezen0,055 buoG iezen 0.25S Dong/lit",Đồng/lít,170,NaN,NaN
836,2014-03-19,Vùng 2,Chiahir-Adiuoohioiithuvohi6nthooinhns,Chiahir-Adiuoohioiithuvohi6nthooinhns,Đồng/lít,NaN,NaN,NaN
843,2014-03-19,Vùng 2,au hoa Dong/it,au hoa Dong/it,Đồng/lít,Ngirng sP du,NaN,NaN
844,2014-03-19,Vùng 2,"azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka","azut No2B (3,0S) Dong/kg a7iitNo2B(35S) Danalka",Đồng/lít,Ngirng SUP dur,NaN,NaN
845,2014-03-19,Vùng 2,hanh,hanh,Đồng/lít,NaN,NaN,NaN
846,2014-03-19,Vùng 2,"lezen0,055 buoG iezen 0.25S Dong/lit","lezen0,055 buoG iezen 0.25S Dong/lit",Đồng/lít,Tgtphg SU Naing hs du,NaN,NaN
860,2016-08-19,Vùng 1,Kang sinh hoc E5 RON95-ll,Kang sinh hoc E5 RON95-ll,Đồng/lít,15220,15520.0,+5
861,2016-08-19,Vùng 1,MI,MI,Đồng/lít,truroc,NaN,NaN
864,2016-08-19,Vùng 1,ang E5 a/l,ang E5 a/l,Đồng/lít,nguyen,NaN,NaN
865,2016-08-19,Vùng 1,angcacloal(urunmien d/l,angcacloal(urunmien d/l,Đồng/lít,nguyen,NaN,NaN
866,2016-08-19,Vùng 1,auhoa d/l,auhoa d/l,Đồng/lít,nguyen,NaN,NaN
867,2016-08-19,Vùng 1,azut cac loai d/kg,azut cac loai d/kg,Đồng/lít,0 6 门,NaN,NaN
868,2016-08-19,Vùng 1,iezen cac loai d/l,iezen cac loai d/l,Đồng/lít,nguyen,NaN,NaN
869,2016-08-19,Vùng 2,MI,MI,Đồng/lít,OS truroc,NaN,NaN
870,2016-08-19,Vùng 2,ang E5 a/l,ang E5 a/l,Đồng/lít,Giu nguyer,NaN,NaN
871,2016-08-19,Vùng 2,angcacloal(urunmien d/l,angcacloal(urunmien d/l,Đồng/lít,Gitp nguyer,NaN,NaN
872,2016-08-19,Vùng 2,auhoa d/l,auhoa d/l,Đồng/lít,Gilp nguyer,NaN,NaN
873,2016-08-19,Vùng 2,azut cac loai d/kg,azut cac loai d/kg,Đồng/lít,Git nquyer,NaN,NaN
874,2016-08-19,Vùng 2,iezen cac loai d/l,iezen cac loai d/l,Đồng/lít,GitP nguyer,NaN,NaN
875,2016-08-19,Vùng 2,usinn noc),usinn noc),Đồng/lít,NaN,NaN,NaN
918,2016-11-19,Vùng 1,Xăng sinh hoc E5 RON95-ll,Xăng sinh hoc E5 RON95-ll,Đồng/lít,16220,16540.0,+5
1059,2015-01-21,Vùng 1,A haa Banallit,A haa Banallit,Đồng/lít,5,NaN,NaN
1061,2015-01-21,Vùng 1,Ghichu:Mirctrichcuthurchientheovanbanso54/,Ghichu:Mirctrichcuthurchientheovanbanso54/,Đồng/lít,06. .01. 1.2014 cua Bo C,NaN,NaN
1065,2015-01-21,Vùng 1,iezencacloai Donqllit,iezencacloai Donqllit,Đồng/lít,5,NaN,NaN
1066,2015-01-21,Vùng 1,ng cac loai Dongllit,ng cac loai Dongllit,Đồng/lít,5,NaN,NaN
1067,2015-01-21,Vùng 2,A haa Banallit,A haa Banallit,Đồng/lít,2,NaN,NaN
1068,2015-01-21,Vùng 2,Ghichu:Mirctrichcuthurchientheovanbanso54/,Ghichu:Mirctrichcuthurchientheovanbanso54/,Đồng/lít,hurong ve viec dieu hanh,NaN,NaN
1072,2015-01-21,Vùng 2,iezencacloai Donqllit,iezencacloai Donqllit,Đồng/lít,3,NaN,NaN
1073,2015-01-21,Vùng 2,ng cac loai Dongllit,ng cac loai Dongllit,Đồng/lít,300,NaN,NaN

In [17]:
bad_rows_2 = [
    305,
    831, 832, 833, 836, 843, 844, 845, 846,
    861, 864, 865, 866, 867, 868,
    869, 870, 871, 872, 873, 874, 875,
    1059, 1061, 1065, 1066, 1067, 1068, 1072, 1073
]

fuel_1 = fuel_1.drop(index=bad_rows_2)

In [18]:
fuel_1["mat_hang_clean"] = fuel_1["mat_hang_clean"].replace({
    "E5RON92": "Xăng sinh học E5 RON 92",
    "Mazút No2B (3.0S)": "Mazút No2B (3,0S)"
})
fuel_1["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu hỏa                          202
Xăng RON 95                      192
Mazút No2B (3,5S)                176
Xăng RON 92                      162
Mazút No2B (3,0S)                160
Mazút No3 (380)                  146
Điêzen 0,05S (DO 0,05S)           98
Điêzen 0,25S                      81
Điêzen 0,05S                      63
Điêzen 0,001S-V (DO 0,001S-V)     52
Xăng sinh học E5 RON 92           50
Xăng RON 92-II                    48
Xăng RON 95-II                    17
Xăng sinh học E5 RON 92-II        15
Kang sinh hoc E5 RON95-ll          1
Xăng sinh hoc E5 RON95-ll          1
Name: count, dtype: int64

In [19]:
fuel_1.loc[
    fuel_1["ngay"].isin([
        pd.Timestamp("2016-08-19"),
        pd.Timestamp("2016-11-19")
    ]),
    ["ngay", "vung", "mat_hang", "gia_moi", "gia_cu", "thay_doi"]
].sort_values(["ngay", "vung"])

          ngay    vung                   mat_hang gia_moi   gia_cu thay_doi
859 2016-08-19  Vùng 1                    Dầu hỏa   10490  10690.0       +2
860 2016-08-19  Vùng 1  Kang sinh hoc E5 RON95-ll   15220  15520.0       +5
862 2016-08-19  Vùng 1          Mazút No2B (3,5S)    8830   9000.0       +3
863 2016-08-19  Vùng 1              Xăng RON95-II   16070  16390.0      +92
915 2016-11-19  Vùng 1                    Dầu hỏa   10960  11170.0       +2
916 2016-11-19  Vùng 1          Mazút No2B (3,5S)    9680   9870.0       +3
917 2016-11-19  Vùng 1              Xăng RON95-II   17070  17410.0      +92
918 2016-11-19  Vùng 1  Xăng sinh hoc E5 RON95-ll   16220  16540.0       +5

In [20]:
fuel_1["mat_hang_clean"] = fuel_1["mat_hang_clean"].replace({
    "Kang sinh hoc E5 RON95-ll": "Xăng sinh học E5 RON 92-II",
    "Xăng sinh hoc E5 RON95-ll": "Xăng sinh học E5 RON 92-II"
})
fuel_1["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu hỏa                          202
Xăng RON 95                      192
Mazút No2B (3,5S)                176
Xăng RON 92                      162
Mazút No2B (3,0S)                160
Mazút No3 (380)                  146
Điêzen 0,05S (DO 0,05S)           98
Điêzen 0,25S                      81
Điêzen 0,05S                      63
Điêzen 0,001S-V (DO 0,001S-V)     52
Xăng sinh học E5 RON 92           50
Xăng RON 92-II                    48
Xăng RON 95-II                    17
Xăng sinh học E5 RON 92-II        17
Name: count, dtype: int64

In [21]:
fuel_1[["gia_moi", "gia_cu"]].dtypes

gia_moi     object
gia_cu     float64
dtype: object

In [22]:
fuel_1["gia_moi"] = pd.to_numeric(
    fuel_1["gia_moi"],
    errors="coerce"
)
fuel_1[["gia_moi", "gia_cu"]].dtypes

gia_moi      int64
gia_cu     float64
dtype: object

In [23]:
fuel_1.loc[
    fuel_1["gia_moi"] <= 0,
    ["ngay", "vung", "mat_hang_clean", "gia_moi"]
]

Empty DataFrame
Columns: [ngay, vung, mat_hang_clean, gia_moi]
Index: []

In [24]:
fuel_1[
    ["ngay", "vung", "mat_hang_clean", "don_vi", "gia_moi"]
].isna().sum()

ngay              0
vung              0
mat_hang_clean    0
don_vi            0
gia_moi           0
dtype: int64

In [25]:
fuel_1 = fuel_1.reset_index(drop=True)
fuel_1.head()

,ngay,gio,vung,mat_hang,don_vi,gia_moi,gia_cu,thay_doi,nguon,url,mat_hang_clean
0,2018-01-01,15:00,Vùng 1,Dầu hỏa,Đồng/lít,13610,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...,Dầu hỏa
1,2018-01-01,15:00,Vùng 1,"Mazút No2B (3,0S)",Đồng/kg,12530,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...,"Mazút No2B (3,0S)"
2,2018-01-01,15:00,Vùng 1,"Mazút No2B (3,5S)",Đồng/kg,12380,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...,"Mazút No2B (3,5S)"
3,2018-01-01,15:00,Vùng 1,Mazút No3 (380),Đồng/kg,12280,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...,Mazút No3 (380)
4,2018-01-01,15:00,Vùng 1,Xăng RON 92,Đồng/lít,18240,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...,Xăng RON 92

In [26]:
fuel_1.duplicated(
    subset=["ngay", "vung", "mat_hang_clean"],
    keep=False
).sum()

np.int64(0)

In [30]:
fuel_1 = fuel_1.sort_values("ngay").reset_index(drop=True)
fuel_1[["ngay", "vung", "mat_hang_clean", "gia_moi"]].head()

        ngay    vung     mat_hang_clean  gia_moi
0 2012-08-01  Vùng 1       Điêzen 0,05S    20800
1 2012-08-01  Vùng 2            Dầu hỏa    21060
2 2012-08-01  Vùng 1            Dầu hỏa    20650
3 2012-08-01  Vùng 1  Mazút No2B (3,0S)    18450
4 2012-08-01  Vùng 1  Mazút No2B (3,5S)    18150

In [31]:
fuel_1.columns.tolist()

['ngay',
 'gio',
 'vung',
 'mat_hang',
 'don_vi',
 'gia_moi',
 'gia_cu',
 'thay_doi',
 'nguon',
 'url',
 'mat_hang_clean']

In [32]:
fuel_1_clean = fuel_1[
    ["ngay", "vung", "mat_hang_clean", "don_vi", "gia_moi"]
].copy()
fuel_1_clean.head()

        ngay    vung     mat_hang_clean    don_vi  gia_moi
0 2012-08-01  Vùng 1       Điêzen 0,05S  Đồng/lít    20800
1 2012-08-01  Vùng 2            Dầu hỏa  Đồng/lít    21060
2 2012-08-01  Vùng 1            Dầu hỏa  Đồng/lít    20650
3 2012-08-01  Vùng 1  Mazút No2B (3,0S)   Đồng/kg    18450
4 2012-08-01  Vùng 1  Mazút No2B (3,5S)   Đồng/kg    18150

In [33]:
fuel_2 = pd.read_excel(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/vietnam_fuel_prices_2017_2018.xlsx"
)
fuel_2.head()

,ngay,gio,vung,mat_hang,don_vi,gia_moi,gia_cu,thay_doi,nguon,url
0,01/01/2018,15:00,Vùng 1,Dầu hỏa,Đồng/lít,13610,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
1,01/01/2018,15:00,Vùng 1,"Mazút No2B (3,0S)",Đồng/kg,12530,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
2,01/01/2018,15:00,Vùng 1,"Mazút No2B (3,5S)",Đồng/kg,12380,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
3,01/01/2018,15:00,Vùng 1,Mazút No3 (380),Đồng/kg,12280,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...
4,01/01/2018,15:00,Vùng 1,Xăng RON 92,Đồng/lít,18240,NaN,NaN,Webgia,https://webgia.com/gia-xang-dau/petrolimex/201...

In [34]:
fuel_2["ngay"] = pd.to_datetime(
    fuel_2["ngay"],
    dayfirst=True
)
fuel_2.dtypes

ngay        datetime64[us]
gio                    str
vung                   str
mat_hang               str
don_vi                 str
gia_moi              int64
gia_cu             float64
thay_doi               str
nguon                  str
url                    str
dtype: object

In [35]:
print(fuel_2["mat_hang"].value_counts(dropna=False).to_string())

mat_hang
Dầu hỏa                          98
Mazút No2B (3,0S)                98
Mazút No2B (3,5S)                98
Mazút No3 (380)                  98
Xăng RON 92                      98
Xăng RON 95                      98
Điêzen 0,05S (DO 0,05S)          98
Điêzen 0,001S-V (DO 0,001S-V)    52
Xăng RON 92-II                   48

In [36]:
fuel_2["mat_hang_clean"] = fuel_2["mat_hang"]
fuel_2[["mat_hang", "mat_hang_clean"]].head()

            mat_hang     mat_hang_clean
0            Dầu hỏa            Dầu hỏa
1  Mazút No2B (3,0S)  Mazút No2B (3,0S)
2  Mazút No2B (3,5S)  Mazút No2B (3,5S)
3    Mazút No3 (380)    Mazút No3 (380)
4        Xăng RON 92        Xăng RON 92

In [37]:
fuel_2.duplicated(
    subset=["ngay", "vung", "mat_hang_clean"],
    keep=False
).sum()

np.int64(0)

In [38]:
fuel_2[
    ["ngay", "vung", "mat_hang_clean", "don_vi", "gia_moi"]
].isna().sum()

ngay              0
vung              0
mat_hang_clean    0
don_vi            0
gia_moi           0
dtype: int64

In [39]:
fuel_2.loc[
    fuel_2["gia_moi"] <= 0,
    ["ngay", "vung", "mat_hang_clean", "gia_moi"]
]

Empty DataFrame
Columns: [ngay, vung, mat_hang_clean, gia_moi]
Index: []

In [42]:
fuel_2 = fuel_2.sort_values("ngay").reset_index(drop=True)
fuel_2[["ngay", "vung", "mat_hang_clean", "gia_moi"]].head()

        ngay    vung     mat_hang_clean  gia_moi
0 2017-01-04  Vùng 1            Dầu hỏa    12250
1 2017-01-04  Vùng 1  Mazút No2B (3,0S)    11520
2 2017-01-04  Vùng 1  Mazút No2B (3,5S)    11120
3 2017-01-04  Vùng 1    Mazút No3 (380)    11020
4 2017-01-04  Vùng 1        Xăng RON 92    17320

In [43]:
fuel_2_clean = fuel_2[
    ["ngay", "vung", "mat_hang_clean", "don_vi", "gia_moi"]
].copy()
fuel_2_clean.head()

        ngay    vung     mat_hang_clean    don_vi  gia_moi
0 2017-01-04  Vùng 1            Dầu hỏa  Đồng/lít    12250
1 2017-01-04  Vùng 1  Mazút No2B (3,0S)   Đồng/kg    11520
2 2017-01-04  Vùng 1  Mazút No2B (3,5S)   Đồng/kg    11120
3 2017-01-04  Vùng 1    Mazút No3 (380)   Đồng/kg    11020
4 2017-01-04  Vùng 1        Xăng RON 92  Đồng/lít    17320

In [44]:
fuel_3 = pd.read_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/vietnam_fuel_prices_2018_2026.csv"
)
fuel_3.head()

,Date,"Dầu DO 0,001S-V","Dầu DO 0,005S-IV","Dầu DO 0,05S-II",Dầu FO 3%S,"Dầu FO 3,5%S",Dầu KO,Xăng E10 RON 95-III,Xăng E5 RON 92-II,Xăng RON 95-III,Xăng RON 95-IV
0,8/22/2018,NaN,17730.0,17680,0.0,0.0,16260.0,NaN,19610,21170,21370.0
1,9/6/2018,NaN,18110.0,18060,0.0,0.0,16550.0,NaN,19910,21470,21670.0
2,9/21/2018,NaN,18170.0,18120,0.0,0.0,16680.0,NaN,20230,21770,21970.0
3,10/6/2018,NaN,18660.0,18610,0.0,0.0,17080.0,NaN,20900,22340,22540.0
4,10/22/2018,NaN,18660.0,18610,0.0,0.0,17080.0,NaN,20680,22200,22400.0

In [45]:
fuel_3["Date"] = pd.to_datetime(
    fuel_3["Date"],
    format="%m/%d/%Y"
)
fuel_3.dtypes

Date                   datetime64[us]
Dầu DO 0,001S-V               float64
Dầu DO 0,005S-IV              float64
Dầu DO 0,05S-II                 int64
Dầu FO 3%S                    float64
Dầu FO 3,5%S                  float64
Dầu KO                        float64
Xăng E10 RON 95-III           float64
Xăng E5 RON 92-II               int64
Xăng RON 95-III                 int64
Xăng RON 95-IV                float64
dtype: object

In [46]:
fuel_3_long = fuel_3.melt(
    id_vars="Date",
    var_name="mat_hang_clean",
    value_name="gia_moi"
)
fuel_3_long.head()

        Date   mat_hang_clean  gia_moi
0 2018-08-22  Dầu DO 0,001S-V      NaN
1 2018-09-06  Dầu DO 0,001S-V      NaN
2 2018-09-21  Dầu DO 0,001S-V      NaN
3 2018-10-06  Dầu DO 0,001S-V      NaN
4 2018-10-22  Dầu DO 0,001S-V      NaN

In [47]:
fuel_3_long.groupby("mat_hang_clean")["gia_moi"].apply(
    lambda x: x.isna().sum()
).sort_values(ascending=False)

mat_hang_clean
Dầu DO 0,005S-IV       270
Xăng RON 95-IV         270
Dầu FO 3%S             248
Dầu FO 3,5%S           247
Xăng E10 RON 95-III    236
Dầu DO 0,001S-V        191
Dầu KO                  11
Dầu DO 0,05S-II          0
Xăng E5 RON 92-II        0
Xăng RON 95-III          0
Name: gia_moi, dtype: int64

In [48]:
fuel_3_long.groupby("mat_hang_clean")["gia_moi"].agg(
    tong_dong="size",
    co_gia="count"
)

                     tong_dong  co_gia
mat_hang_clean
Dầu DO 0,001S-V            280      89
Dầu DO 0,005S-IV           280      10
Dầu DO 0,05S-II            280     280
Dầu FO 3%S                 280      32
Dầu FO 3,5%S               280      33
Dầu KO                     280     269
Xăng E10 RON 95-III        280      44
Xăng E5 RON 92-II          280     280
Xăng RON 95-III            280     280
Xăng RON 95-IV             280      10

In [49]:
fuel_3_long.groupby("mat_hang_clean")["gia_moi"].apply(
    lambda x: (x == 0).sum()
).sort_values(ascending=False)

mat_hang_clean
Dầu FO 3,5%S           32
Dầu FO 3%S             32
Dầu DO 0,005S-IV        0
Dầu DO 0,001S-V         0
Dầu DO 0,05S-II         0
Dầu KO                  0
Xăng E10 RON 95-III     0
Xăng E5 RON 92-II       0
Xăng RON 95-III         0
Xăng RON 95-IV          0
Name: gia_moi, dtype: int64

In [50]:
fuel_3_long.loc[
    fuel_3_long["mat_hang_clean"].isin([
        "Dầu FO 3%S",
        "Dầu FO 3,5%S"
    ]) & fuel_3_long["gia_moi"].notna()
].sort_values(["mat_hang_clean", "Date"])

           Date mat_hang_clean  gia_moi
840  2018-08-22     Dầu FO 3%S      0.0
841  2018-09-06     Dầu FO 3%S      0.0
842  2018-09-21     Dầu FO 3%S      0.0
843  2018-10-06     Dầu FO 3%S      0.0
844  2018-10-22     Dầu FO 3%S      0.0
...         ...            ...      ...
1148 2019-10-16   Dầu FO 3,5%S      0.0
1149 2019-10-31   Dầu FO 3,5%S      0.0
1150 2019-11-15   Dầu FO 3,5%S      0.0
1151 2019-11-30   Dầu FO 3,5%S      0.0
1294 2024-05-30   Dầu FO 3,5%S  17530.0

[65 rows x 3 columns]

In [51]:
import numpy as np

fuel_3_long["gia_moi"] = fuel_3_long["gia_moi"].replace(0, np.nan)
(fuel_3_long["gia_moi"] == 0).sum()

np.int64(0)

In [52]:
fuel_3_long.groupby("mat_hang_clean")["gia_moi"].count().sort_values()

mat_hang_clean
Dầu FO 3%S               0
Dầu FO 3,5%S             1
Dầu DO 0,005S-IV        10
Xăng RON 95-IV          10
Xăng E10 RON 95-III     44
Dầu DO 0,001S-V         89
Dầu KO                 269
Dầu DO 0,05S-II        280
Xăng E5 RON 92-II      280
Xăng RON 95-III        280
Name: gia_moi, dtype: int64

In [53]:
fuel_3_long.dropna(subset=["gia_moi"]).groupby("mat_hang_clean").agg(
    so_gia=("gia_moi", "count"),
    tu_ngay=("Date", "min"),
    den_ngay=("Date", "max")
).sort_values("so_gia")

                     so_gia    tu_ngay   den_ngay
mat_hang_clean
Dầu FO 3,5%S              1 2024-05-30 2024-05-30
Dầu DO 0,005S-IV         10 2018-08-22 2019-01-01
Xăng RON 95-IV           10 2018-08-22 2019-01-01
Xăng E10 RON 95-III      44 2025-07-31 2026-04-16
Dầu DO 0,001S-V          89 2024-09-26 2026-04-16
Dầu KO                  269 2018-08-22 2026-03-07
Xăng E5 RON 92-II       280 2018-08-22 2026-04-16
Dầu DO 0,05S-II         280 2018-08-22 2026-04-16
Xăng RON 95-III         280 2018-08-22 2026-04-16

In [54]:
fuel_3_long = fuel_3_long[
    fuel_3_long["Date"] <= "2024-12-31"
].copy()
fuel_3_long["Date"].max()

Timestamp('2024-12-26 00:00:00')

In [55]:
fuel_3_long.groupby("mat_hang_clean")["gia_moi"].count().sort_values()

mat_hang_clean
Dầu FO 3%S               0
Xăng E10 RON 95-III      0
Dầu FO 3,5%S             1
Dầu DO 0,005S-IV        10
Xăng RON 95-IV          10
Dầu DO 0,001S-V         14
Dầu KO                 205
Dầu DO 0,05S-II        205
Xăng E5 RON 92-II      205
Xăng RON 95-III        205
Name: gia_moi, dtype: int64

In [56]:
fuel_3_long = fuel_3_long.dropna(
    subset=["gia_moi"]
).reset_index(drop=True)
fuel_3_long["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu DO 0,05S-II      205
Dầu KO               205
Xăng E5 RON 92-II    205
Xăng RON 95-III      205
Dầu DO 0,001S-V       14
Dầu DO 0,005S-IV      10
Xăng RON 95-IV        10
Dầu FO 3,5%S           1
Name: count, dtype: int64

In [57]:
fuel_3_long[
    fuel_3_long["mat_hang_clean"].isin([
        "Dầu FO 3,5%S",
        "Dầu DO 0,005S-IV",
        "Xăng RON 95-IV",
        "Dầu DO 0,001S-V"
    ])
].sort_values(["mat_hang_clean", "Date"])

          Date    mat_hang_clean  gia_moi
0   2024-09-26   Dầu DO 0,001S-V  17850.0
1   2024-10-03   Dầu DO 0,001S-V  17510.0
2   2024-10-10   Dầu DO 0,001S-V  18600.0
3   2024-10-17   Dầu DO 0,001S-V  18570.0
4   2024-10-24   Dầu DO 0,001S-V  18310.0
5   2024-10-31   Dầu DO 0,001S-V  18360.0
6   2024-11-07   Dầu DO 0,001S-V  19120.0
7   2024-11-14   Dầu DO 0,001S-V  18660.0
8   2024-11-21   Dầu DO 0,001S-V  18610.0
9   2024-11-28   Dầu DO 0,001S-V  18930.0
10  2024-12-05   Dầu DO 0,001S-V  18570.0
11  2024-12-12   Dầu DO 0,001S-V  18440.0
12  2024-12-19   Dầu DO 0,001S-V  18980.0
13  2024-12-26   Dầu DO 0,001S-V  18840.0
14  2018-08-22  Dầu DO 0,005S-IV  17730.0
15  2018-09-06  Dầu DO 0,005S-IV  18110.0
16  2018-09-21  Dầu DO 0,005S-IV  18170.0
17  2018-10-06  Dầu DO 0,005S-IV  18660.0
18  2018-10-22  Dầu DO 0,005S-IV  18660.0
19  2018-11-06  Dầu DO 0,005S-IV  18590.0
20  2018-11-21  Dầu DO 0,005S-IV  17680.0
21  2018-12-06  Dầu DO 0,005S-IV  16300.0
22  2018-12-21  Dầu DO 0,005S-IV  16050.0
23  2019-01-01  Dầu DO 0,005S-IV  14950.0
229 2024-05-30      Dầu FO 3,5%S  17530.0
845 2018-08-22    Xăng RON 95-IV  21370.0
846 2018-09-06    Xăng RON 95-IV  21670.0
847 2018-09-21    Xăng RON 95-IV  21970.0
848 2018-10-06    Xăng RON 95-IV  22540.0
849 2018-10-22    Xăng RON 95-IV  22400.0
850 2018-11-06    Xăng RON 95-IV  21260.0
851 2018-11-21    Xăng RON 95-IV  20170.0
852 2018-12-06    Xăng RON 95-IV  18650.0
853 2018-12-21    Xăng RON 95-IV  18340.0
854 2019-01-01    Xăng RON 95-IV  17800.0

In [58]:
fuel_3_long = fuel_3_long[
    fuel_3_long["mat_hang_clean"] != "Dầu FO 3,5%S"
].reset_index(drop=True)
fuel_3_long["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu DO 0,05S-II      205
Dầu KO               205
Xăng E5 RON 92-II    205
Xăng RON 95-III      205
Dầu DO 0,001S-V       14
Dầu DO 0,005S-IV      10
Xăng RON 95-IV        10
Name: count, dtype: int64

In [59]:
fuel_3_long = fuel_3_long.rename(
    columns={"Date": "ngay"}
)
fuel_3_long.head()

        ngay   mat_hang_clean  gia_moi
0 2024-09-26  Dầu DO 0,001S-V  17850.0
1 2024-10-03  Dầu DO 0,001S-V  17510.0
2 2024-10-10  Dầu DO 0,001S-V  18600.0
3 2024-10-17  Dầu DO 0,001S-V  18570.0
4 2024-10-24  Dầu DO 0,001S-V  18310.0

In [60]:
print("FILE 1:")
print(sorted(fuel_1_clean["mat_hang_clean"].unique()))

print("\nFILE 2:")
print(sorted(fuel_2_clean["mat_hang_clean"].unique()))

print("\nFILE 3:")
print(sorted(fuel_3_long["mat_hang_clean"].unique()))

FILE 1:
['Dầu hỏa', 'Mazút No2B (3,0S)', 'Mazút No2B (3,5S)', 'Mazút No3 (380)', 'Xăng RON 92', 'Xăng RON 92-II', 'Xăng RON 95', 'Xăng RON 95-II', 'Xăng sinh học E5 RON 92', 'Xăng sinh học E5 RON 92-II', 'Điêzen 0,001S-V (DO 0,001S-V)', 'Điêzen 0,05S', 'Điêzen 0,05S (DO 0,05S)', 'Điêzen 0,25S']

FILE 2:
['Dầu hỏa', 'Mazút No2B (3,0S)', 'Mazút No2B (3,5S)', 'Mazút No3 (380)', 'Xăng RON 92', 'Xăng RON 92-II', 'Xăng RON 95', 'Điêzen 0,001S-V (DO 0,001S-V)', 'Điêzen 0,05S (DO 0,05S)']

FILE 3:
['Dầu DO 0,001S-V', 'Dầu DO 0,005S-IV', 'Dầu DO 0,05S-II', 'Dầu KO', 'Xăng E5 RON 92-II', 'Xăng RON 95-III', 'Xăng RON 95-IV']

In [61]:
fuel_3_long["mat_hang_clean"] = fuel_3_long["mat_hang_clean"].replace({
    "Dầu KO": "Dầu hỏa"
})
fuel_3_long["mat_hang_clean"].unique()

<StringArray>
[  'Dầu DO 0,001S-V',  'Dầu DO 0,005S-IV',   'Dầu DO 0,05S-II',
           'Dầu hỏa', 'Xăng E5 RON 92-II',   'Xăng RON 95-III',
    'Xăng RON 95-IV']
Length: 7, dtype: str

In [62]:
fuel_1_clean["mat_hang_clean"] = fuel_1_clean["mat_hang_clean"].replace({
    "Điêzen 0,001S-V (DO 0,001S-V)": "Dầu DO 0,001S-V"
})

fuel_2_clean["mat_hang_clean"] = fuel_2_clean["mat_hang_clean"].replace({
    "Điêzen 0,001S-V (DO 0,001S-V)": "Dầu DO 0,001S-V"
})
print(sorted(fuel_1_clean["mat_hang_clean"].unique()))
print(sorted(fuel_2_clean["mat_hang_clean"].unique()))

['Dầu DO 0,001S-V', 'Dầu hỏa', 'Mazút No2B (3,0S)', 'Mazút No2B (3,5S)', 'Mazút No3 (380)', 'Xăng RON 92', 'Xăng RON 92-II', 'Xăng RON 95', 'Xăng RON 95-II', 'Xăng sinh học E5 RON 92', 'Xăng sinh học E5 RON 92-II', 'Điêzen 0,05S', 'Điêzen 0,05S (DO 0,05S)', 'Điêzen 0,25S']
['Dầu DO 0,001S-V', 'Dầu hỏa', 'Mazút No2B (3,0S)', 'Mazút No2B (3,5S)', 'Mazút No3 (380)', 'Xăng RON 92', 'Xăng RON 92-II', 'Xăng RON 95', 'Điêzen 0,05S (DO 0,05S)']

In [63]:
fuel_1_clean["mat_hang_clean"] = fuel_1_clean["mat_hang_clean"].replace({
    "Điêzen 0,05S": "Dầu DO 0,05S",
    "Điêzen 0,05S (DO 0,05S)": "Dầu DO 0,05S"
})

fuel_2_clean["mat_hang_clean"] = fuel_2_clean["mat_hang_clean"].replace({
    "Điêzen 0,05S (DO 0,05S)": "Dầu DO 0,05S"
})
print(fuel_1_clean["mat_hang_clean"].value_counts())
print(fuel_2_clean["mat_hang_clean"].value_counts())

mat_hang_clean
Dầu hỏa                       202
Xăng RON 95                   192
Mazút No2B (3,5S)             176
Xăng RON 92                   162
Dầu DO 0,05S                  161
Mazút No2B (3,0S)             160
Mazút No3 (380)               146
Điêzen 0,25S                   81
Dầu DO 0,001S-V                52
Xăng sinh học E5 RON 92        50
Xăng RON 92-II                 48
Xăng RON 95-II                 17
Xăng sinh học E5 RON 92-II     17
Name: count, dtype: int64
mat_hang_clean
Dầu hỏa              98
Mazút No2B (3,0S)    98
Mazút No2B (3,5S)    98
Mazút No3 (380)      98
Xăng RON 92          98
Xăng RON 95          98
Dầu DO 0,05S         98
Dầu DO 0,001S-V      52
Xăng RON 92-II       48
Name: count, dtype: int64

In [64]:
fuel_3_long["mat_hang_clean"] = fuel_3_long["mat_hang_clean"].replace({
    "Dầu DO 0,05S-II": "Dầu DO 0,05S"
})
fuel_3_long["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu DO 0,05S         205
Dầu hỏa              205
Xăng E5 RON 92-II    205
Xăng RON 95-III      205
Dầu DO 0,001S-V       14
Dầu DO 0,005S-IV      10
Xăng RON 95-IV        10
Name: count, dtype: int64

In [66]:
fuel_3_long["mat_hang_clean"] = fuel_3_long["mat_hang_clean"].replace({
    "Xăng E5 RON 92-II": "Xăng sinh học E5 RON 92-II"
})
fuel_3_long["mat_hang_clean"].value_counts()

mat_hang_clean
Dầu DO 0,05S                  205
Dầu hỏa                       205
Xăng sinh học E5 RON 92-II    205
Xăng RON 95-III               205
Dầu DO 0,001S-V                14
Dầu DO 0,005S-IV               10
Xăng RON 95-IV                 10
Name: count, dtype: int64

In [67]:
compare_ron95 = fuel_2_clean[
    fuel_2_clean["mat_hang_clean"] == "Xăng RON 95"
][["ngay", "vung", "gia_moi"]].merge(
    fuel_3_long[
        fuel_3_long["mat_hang_clean"] == "Xăng RON 95-III"
    ][["ngay", "gia_moi"]],
    on="ngay",
    how="inner",
    suffixes=("_file2", "_file3")
)

compare_ron95

         ngay    vung  gia_moi_file2  gia_moi_file3
0  2018-08-22  Vùng 2          21740        21170.0
1  2018-08-22  Vùng 1          21320        21170.0
2  2018-09-06  Vùng 2          22050        21470.0
3  2018-09-06  Vùng 1          21620        21470.0
4  2018-09-21  Vùng 1          21920        21770.0
5  2018-09-21  Vùng 2          22350        21770.0
6  2018-10-06  Vùng 2          22930        22340.0
7  2018-10-06  Vùng 1          22490        22340.0
8  2018-10-22  Vùng 2          22790        22200.0
9  2018-10-22  Vùng 1          22350        22200.0
10 2018-11-06  Vùng 1          21210        21060.0
11 2018-11-06  Vùng 2          21630        21060.0
12 2018-11-21  Vùng 2          20520        19970.0
13 2018-11-21  Vùng 1          20120        19970.0
14 2018-12-06  Vùng 2          18970        18450.0
15 2018-12-06  Vùng 1          18600        18450.0
16 2018-12-21  Vùng 2          18650        18140.0
17 2018-12-21  Vùng 1          18290        18140.0

In [68]:
compare_ron95_iv = fuel_2_clean[
    fuel_2_clean["mat_hang_clean"] == "Xăng RON 95"
][["ngay", "vung", "gia_moi"]].merge(
    fuel_3_long[
        fuel_3_long["mat_hang_clean"] == "Xăng RON 95-IV"
    ][["ngay", "gia_moi"]],
    on="ngay",
    how="inner",
    suffixes=("_file2", "_file3")
)

compare_ron95_iv

         ngay    vung  gia_moi_file2  gia_moi_file3
0  2018-08-22  Vùng 2          21740        21370.0
1  2018-08-22  Vùng 1          21320        21370.0
2  2018-09-06  Vùng 2          22050        21670.0
3  2018-09-06  Vùng 1          21620        21670.0
4  2018-09-21  Vùng 1          21920        21970.0
5  2018-09-21  Vùng 2          22350        21970.0
6  2018-10-06  Vùng 2          22930        22540.0
7  2018-10-06  Vùng 1          22490        22540.0
8  2018-10-22  Vùng 2          22790        22400.0
9  2018-10-22  Vùng 1          22350        22400.0
10 2018-11-06  Vùng 1          21210        21260.0
11 2018-11-06  Vùng 2          21630        21260.0
12 2018-11-21  Vùng 2          20520        20170.0
13 2018-11-21  Vùng 1          20120        20170.0
14 2018-12-06  Vùng 2          18970        18650.0
15 2018-12-06  Vùng 1          18600        18650.0
16 2018-12-21  Vùng 2          18650        18340.0
17 2018-12-21  Vùng 1          18290        18340.0

In [72]:
print("FILE 1:", fuel_1_clean["ngay"].min(), "->", fuel_1_clean["ngay"].max())
print("FILE 2:", fuel_2_clean["ngay"].min(), "->", fuel_2_clean["ngay"].max())
print("FILE 3:", fuel_3_long["ngay"].min(), "->", fuel_3_long["ngay"].max())

FILE 1: 2012-08-01 00:00:00 -> 2018-12-21 00:00:00
FILE 2: 2017-01-04 00:00:00 -> 2018-12-21 00:00:00
FILE 3: 2018-08-22 00:00:00 -> 2024-12-26 00:00:00

In [74]:
overlap_12 = fuel_1_clean.merge(
    fuel_2_clean,
    on=["ngay", "vung", "mat_hang_clean"],
    how="inner",
    suffixes=("_file1", "_file2")
)

overlap_12.head()

,ngay,vung,mat_hang_clean,don_vi_file1,gia_moi_file1,don_vi_file2,gia_moi_file2
0,2017-01-04,Vùng 1,"Dầu DO 0,05S",Đồng/lít,13750,Đồng/lít,13750
1,2017-01-04,Vùng 1,Xăng RON 95,Đồng/lít,18440,Đồng/lít,18440
2,2017-01-04,Vùng 2,"Mazút No2B (3,5S)",Đồng/kg,11120,Đồng/kg,11120
3,2017-01-04,Vùng 1,Dầu hỏa,Đồng/lít,12250,Đồng/lít,12250
4,2017-01-04,Vùng 2,"Mazút No2B (3,0S)",Đồng/kg,11750,Đồng/kg,11750

In [75]:
(overlap_12["gia_moi_file1"] != overlap_12["gia_moi_file2"]).sum()

np.int64(0)

In [76]:
overlap_12.shape

(786, 7)

In [78]:
fuel_12 = pd.concat(
    [fuel_1_clean, fuel_2_clean],
    ignore_index=True
)

fuel_12 = fuel_12.drop_duplicates(
    subset=["ngay", "vung", "mat_hang_clean"],
    keep="first"
).reset_index(drop=True)
fuel_12.shape

(1464, 5)

In [79]:
compare_kerosene = fuel_2_clean[
    fuel_2_clean["mat_hang_clean"] == "Dầu hỏa"
][["ngay", "vung", "gia_moi"]].merge(
    fuel_3_long[
        fuel_3_long["mat_hang_clean"] == "Dầu hỏa"
    ][["ngay", "gia_moi"]],
    on="ngay",
    how="inner",
    suffixes=("_file2", "_file3")
)

compare_kerosene

         ngay    vung  gia_moi_file2  gia_moi_file3
0  2018-08-22  Vùng 2          16580        16260.0
1  2018-08-22  Vùng 1          16260        16260.0
2  2018-09-06  Vùng 2          16880        16550.0
3  2018-09-06  Vùng 1          16550        16550.0
4  2018-09-21  Vùng 2          17010        16680.0
5  2018-09-21  Vùng 1          16680        16680.0
6  2018-10-06  Vùng 1          17080        17080.0
7  2018-10-06  Vùng 2          17420        17080.0
8  2018-10-22  Vùng 2          17420        17080.0
9  2018-10-22  Vùng 1          17080        17080.0
10 2018-11-06  Vùng 2          17420        17080.0
11 2018-11-06  Vùng 1          17080        17080.0
12 2018-11-21  Vùng 1          16240        16240.0
13 2018-11-21  Vùng 2          16560        16240.0
14 2018-12-06  Vùng 2          15550        15250.0
15 2018-12-06  Vùng 1          15250        15250.0
16 2018-12-21  Vùng 2          15300        15000.0
17 2018-12-21  Vùng 1          15000        15000.0

In [80]:
compare_do = fuel_2_clean[
    fuel_2_clean["mat_hang_clean"] == "Dầu DO 0,05S"
][["ngay", "vung", "gia_moi"]].merge(
    fuel_3_long[
        fuel_3_long["mat_hang_clean"] == "Dầu DO 0,05S"
    ][["ngay", "gia_moi"]],
    on="ngay",
    how="inner",
    suffixes=("_file2", "_file3")
)

compare_do

         ngay    vung  gia_moi_file2  gia_moi_file3
0  2018-08-22  Vùng 2          18030        17680.0
1  2018-08-22  Vùng 1          17680        17680.0
2  2018-09-06  Vùng 1          18060        18060.0
3  2018-09-06  Vùng 2          18420        18060.0
4  2018-09-21  Vùng 1          18120        18120.0
5  2018-09-21  Vùng 2          18480        18120.0
6  2018-10-06  Vùng 2          18980        18610.0
7  2018-10-06  Vùng 1          18610        18610.0
8  2018-10-22  Vùng 1          18610        18610.0
9  2018-10-22  Vùng 2          18980        18610.0
10 2018-11-06  Vùng 1          18540        18540.0
11 2018-11-06  Vùng 2          18910        18540.0
12 2018-11-21  Vùng 2          17980        17630.0
13 2018-11-21  Vùng 1          17630        17630.0
14 2018-12-06  Vùng 2          16570        16250.0
15 2018-12-06  Vùng 1          16250        16250.0
16 2018-12-21  Vùng 2          16320        16000.0
17 2018-12-21  Vùng 1          16000        16000.0

In [81]:
fuel_12_v1 = fuel_12[
    fuel_12["vung"] == "Vùng 1"
][
    ["ngay", "mat_hang_clean", "gia_moi"]
].copy()
fuel_12_v1.head()

        ngay     mat_hang_clean  gia_moi
0 2012-08-01       Dầu DO 0,05S    20800
2 2012-08-01            Dầu hỏa    20650
3 2012-08-01  Mazút No2B (3,0S)    18450
4 2012-08-01  Mazút No2B (3,5S)    18150
5 2012-08-01        Xăng RON 95    22400

In [82]:
fuel_3_clean = fuel_3_long[
    ["ngay", "mat_hang_clean", "gia_moi"]
].copy()
fuel_3_clean.head()

        ngay   mat_hang_clean  gia_moi
0 2024-09-26  Dầu DO 0,001S-V  17850.0
1 2024-10-03  Dầu DO 0,001S-V  17510.0
2 2024-10-10  Dầu DO 0,001S-V  18600.0
3 2024-10-17  Dầu DO 0,001S-V  18570.0
4 2024-10-24  Dầu DO 0,001S-V  18310.0

In [83]:
overlap_123 = fuel_12_v1.merge(
    fuel_3_clean,
    on=["ngay", "mat_hang_clean"],
    how="inner",
    suffixes=("_file12", "_file3")
)

overlap_123.head()

        ngay mat_hang_clean  gia_moi_file12  gia_moi_file3
0 2018-08-22        Dầu hỏa           16260        16260.0
1 2018-08-22   Dầu DO 0,05S           17680        17680.0
2 2018-09-06   Dầu DO 0,05S           18060        18060.0
3 2018-09-06        Dầu hỏa           16550        16550.0
4 2018-09-21   Dầu DO 0,05S           18120        18120.0

In [84]:
overlap_123.shape

(18, 4)

In [85]:
(overlap_123["gia_moi_file12"] != overlap_123["gia_moi_file3"]).sum()

np.int64(0)

In [ ]:
fuel_all = pd.concat(
    [fuel_12_v1, fuel_3_clean],
    ignore_index=True
)

fuel_all = fuel_all.drop_duplicates(
    subset=["ngay", "mat_hang_clean"],
    keep="first"
).reset_index(drop=True)
fuel_all.shape

(1648, 3)

In [87]:
fuel_all.duplicated(
    subset=["ngay", "mat_hang_clean"]
).sum()

np.int64(0)

In [90]:
fuel_all = fuel_all.sort_values("ngay").reset_index(drop=True)
fuel_all.head(20)

         ngay     mat_hang_clean  gia_moi
0  2012-08-01       Dầu DO 0,05S  20800.0
1  2012-08-01            Dầu hỏa  20650.0
2  2012-08-01  Mazút No2B (3,0S)  18450.0
3  2012-08-01  Mazút No2B (3,5S)  18150.0
4  2012-08-01        Xăng RON 95  22400.0
5  2012-08-01       Điêzen 0,25S  20750.0
6  2012-08-01    Mazút No3 (380)  18050.0
7  2012-08-01        Xăng RON 92  21900.0
8  2012-08-13            Dầu hỏa  21450.0
9  2012-08-13        Xăng RON 95  23500.0
10 2012-08-13  Mazút No2B (3,0S)  18950.0
11 2012-08-13       Dầu DO 0,05S  21550.0
12 2012-08-13        Xăng RON 92  23000.0
13 2012-08-13       Điêzen 0,25S  21500.0
14 2012-08-13    Mazút No3 (380)  18550.0
15 2012-08-13  Mazút No2B (3,5S)  18650.0
16 2012-08-28            Dầu hỏa  21900.0
17 2012-08-28  Mazút No2B (3,5S)  18650.0
18 2012-08-28       Điêzen 0,25S  21800.0
19 2012-08-28       Dầu DO 0,05S  21850.0

In [91]:
fuel_all.to_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/interim/fuel_prices_clean.csv",
    index=False,
    encoding="utf-8-sig"
)