In [1]:
import pandas as pd

brent = pd.read_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/brent_crude_oil_monthly.csv"
)

wti = pd.read_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/wti_crude_oil_monthly.csv"
)

In [2]:
brent.head()

         Date  Price
0  1987-05-15  18.58
1  1987-06-15  18.86
2  1987-07-15  19.86
3  1987-08-15  18.98
4  1987-09-15  18.31

In [3]:
wti.head()

         Date  Price
0  1986-01-15  22.93
1  1986-02-15  15.46
2  1986-03-15  12.61
3  1986-04-15  12.84
4  1986-05-15  15.38

In [4]:
brent["Date"] = pd.to_datetime(brent["Date"])
wti["Date"] = pd.to_datetime(wti["Date"])
print(brent.dtypes)
print(wti.dtypes)

Date     datetime64[us]
Price           float64
dtype: object
Date     datetime64[us]
Price           float64
dtype: object

In [5]:
brent = brent[
    (brent["Date"] >= "2012-01-01") &
    (brent["Date"] <= "2024-12-31")
].copy()

wti = wti[
    (wti["Date"] >= "2012-01-01") &
    (wti["Date"] <= "2024-12-31")
].copy()
print("Brent:", brent["Date"].min(), "->", brent["Date"].max())
print("WTI:", wti["Date"].min(), "->", wti["Date"].max())

Brent: 2012-01-15 00:00:00 -> 2024-12-15 00:00:00
WTI: 2012-01-15 00:00:00 -> 2024-12-15 00:00:00

In [6]:
brent["MonthYear"] = brent["Date"].dt.to_period("M")
wti["MonthYear"] = wti["Date"].dt.to_period("M")
print(brent[["Date", "MonthYear", "Price"]].head())
print(wti[["Date", "MonthYear", "Price"]].head())

          Date MonthYear   Price
296 2012-01-15   2012-01  110.69
297 2012-02-15   2012-02  119.33
298 2012-03-15   2012-03  125.45
299 2012-04-15   2012-04  119.75
300 2012-05-15   2012-05  110.34
          Date MonthYear   Price
312 2012-01-15   2012-01  100.27
313 2012-02-15   2012-02  102.20
314 2012-03-15   2012-03  106.16
315 2012-04-15   2012-04  103.32
316 2012-05-15   2012-05   94.66

In [7]:
brent = brent.rename(columns={"Price": "Brent"})
wti = wti.rename(columns={"Price": "WTI"})
print(brent.head())
print(wti.head())

          Date   Brent MonthYear
296 2012-01-15  110.69   2012-01
297 2012-02-15  119.33   2012-02
298 2012-03-15  125.45   2012-03
299 2012-04-15  119.75   2012-04
300 2012-05-15  110.34   2012-05
          Date     WTI MonthYear
312 2012-01-15  100.27   2012-01
313 2012-02-15  102.20   2012-02
314 2012-03-15  106.16   2012-03
315 2012-04-15  103.32   2012-04
316 2012-05-15   94.66   2012-05

In [8]:
oil_global = brent[["MonthYear", "Brent"]].merge(
    wti[["MonthYear", "WTI"]],
    on="MonthYear",
    how="inner"
)
oil_global.head()

  MonthYear   Brent     WTI
0   2012-01  110.69  100.27
1   2012-02  119.33  102.20
2   2012-03  125.45  106.16
3   2012-04  119.75  103.32
4   2012-05  110.34   94.66

In [9]:
print(oil_global.shape)

(156, 3)

In [10]:
oil_global.isna().sum()

MonthYear    0
Brent        0
WTI          0
dtype: int64

In [11]:
oil_global[
    (oil_global["Brent"] < 0) |
    (oil_global["WTI"] < 0)
]

Empty DataFrame
Columns: [MonthYear, Brent, WTI]
Index: []

In [12]:
oil_global.to_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/interim/global_oil_monthly.csv",
    index=False,
    encoding="utf-8-sig"
)