In [1]:
import pandas as pd

brent = pd.read_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/brent_crude_oil_monthly.csv"
)

wti = pd.read_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/raw/wti_crude_oil_monthly.csv"
)

In [2]:
brent.head()

         Date  Price
0  1987-05-15  18.58
1  1987-06-15  18.86
2  1987-07-15  19.86
3  1987-08-15  18.98
4  1987-09-15  18.31

In [3]:
wti.head()

         Date  Price
0  1986-01-15  22.93
1  1986-02-15  15.46
2  1986-03-15  12.61
3  1986-04-15  12.84
4  1986-05-15  15.38

In [4]:
brent["Date"] = pd.to_datetime(brent["Date"])
wti["Date"] = pd.to_datetime(wti["Date"])
print(brent.dtypes)
print(wti.dtypes)

Date     datetime64[us]
Price           float64
dtype: object
Date     datetime64[us]
Price           float64
dtype: object

In [5]:
brent = brent[
    (brent["Date"] >= "2011-09-01") &
    (brent["Date"] <= "2024-12-31")
].copy()

wti = wti[
    (wti["Date"] >= "2011-09-01") &
    (wti["Date"] <= "2024-12-31")
].copy()
print("Brent:", brent["Date"].min(), "->", brent["Date"].max())
print("WTI:", wti["Date"].min(), "->", wti["Date"].max())

Brent: 2011-09-15 00:00:00 -> 2024-12-15 00:00:00
WTI: 2011-09-15 00:00:00 -> 2024-12-15 00:00:00

In [6]:
brent["MonthYear"] = brent["Date"].dt.to_period("M")
wti["MonthYear"] = wti["Date"].dt.to_period("M")
print(brent[["Date", "MonthYear", "Price"]].head())
print(wti[["Date", "MonthYear", "Price"]].head())

          Date MonthYear   Price
292 2011-09-15   2011-09  112.83
293 2011-10-15   2011-10  109.55
294 2011-11-15   2011-11  110.77
295 2011-12-15   2011-12  107.87
296 2012-01-15   2012-01  110.69
          Date MonthYear   Price
308 2011-09-15   2011-09   85.52
309 2011-10-15   2011-10   86.32
310 2011-11-15   2011-11   97.16
311 2011-12-15   2011-12   98.56
312 2012-01-15   2012-01  100.27

In [7]:
brent = brent.rename(columns={"Price": "Brent"})
wti = wti.rename(columns={"Price": "WTI"})
print(brent.head())
print(wti.head())

          Date   Brent MonthYear
292 2011-09-15  112.83   2011-09
293 2011-10-15  109.55   2011-10
294 2011-11-15  110.77   2011-11
295 2011-12-15  107.87   2011-12
296 2012-01-15  110.69   2012-01
          Date     WTI MonthYear
308 2011-09-15   85.52   2011-09
309 2011-10-15   86.32   2011-10
310 2011-11-15   97.16   2011-11
311 2011-12-15   98.56   2011-12
312 2012-01-15  100.27   2012-01

In [8]:
oil_global = brent[["MonthYear", "Brent"]].merge(
    wti[["MonthYear", "WTI"]],
    on="MonthYear",
    how="inner"
)
oil_global.head()

  MonthYear   Brent     WTI
0   2011-09  112.83   85.52
1   2011-10  109.55   86.32
2   2011-11  110.77   97.16
3   2011-12  107.87   98.56
4   2012-01  110.69  100.27

In [9]:
print(oil_global.shape)

(160, 3)

In [10]:
oil_global.isna().sum()

MonthYear    0
Brent        0
WTI          0
dtype: int64

In [11]:
oil_global[
    (oil_global["Brent"] < 0) |
    (oil_global["WTI"] < 0)
]

Empty DataFrame
Columns: [MonthYear, Brent, WTI]
Index: []

In [12]:
brent_monthly = oil_global[
    ["MonthYear", "Brent"]
].copy()

wti_monthly = oil_global[
    ["MonthYear", "WTI"]
].copy()

brent_monthly.to_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/interim/brent_monthly.csv",
    index=False,
    encoding="utf-8-sig"
)

wti_monthly.to_csv(
    "d:/HK3 - năm 3/Đồ Án/Code/vietnam-transportation-cpi-forecasting/data/interim/wti_monthly.csv",
    index=False,
    encoding="utf-8-sig"
)